### ISSUE TITLE
consider reading defaults for browser configuration from predefined system variables like SELENIDEJS_BASE_URL

### ISSUE THREAD

**Issue by yashaka** [KnowledgeExpert/selenidejs#100]
subj.

Probabably I would use names like `SELENIDEJS_baseUrl` where camelCased `baseUrl` part is exactly the same as in configuration...

**Comment by yashaka** [comment]
contr-arguments:
- will make the lib less KISS, will increase the amount of docs with info that is not uniqui to SelenideJS, because this is actually a technique that can be easily implemented on the test framework side... that most probably will be implemented nevertheless...

**Comment by AleksanderPopov** [comment]
I would save selenidejs docs from extra info when possible, and this one doesn't seem like super important...

I suggest to close this right now, and maybe return in the future when we will decide that it would help users more than just to avoid a single line of code...

**Comment by AleksanderPopov** [comment]
Also if we would introduce env variabale for `baseUrl` which we pass while building `Browser`, the reasonable questions is - why don't we create variables for `timeout`, `windowHeight`, `windowWidth`, and maybe others...which forces to create docs for that as well...

@yashaka

**Comment by yashaka** [comment]
yes, sure, baseUrl, was just an example... if we decide to do it for here, then we have to do it everywere... 
Let's keep it KISS and close for now.
