### ISSUE TITLE
Usefull stacktraces

### ISSUE THREAD

**Issue by AleksanderPopov** [KnowledgeExpert/selenidejs#112]
Since we throwing errors from selenidejs manually, maybe we can try to patch the stack traces and cut from there all the calls from selenidejs inner entities? to leave something like

```
mywidget:44
mypageobject:12
myspecfile:56
```
instead of
```
nodemodules selenidejs wait
nodemodules selenidejs condition
nodemodules selenidejs element
...
mywidget:44
mypageobject:12
myspecfile:56
```

That can increase the quality of stack traces since most of the users probably not interested in that `node_modules` calls part.

How do you think @yashaka ?

**Comment by yashaka** [comment]
Probably we can do it... if do it in a configurable way... not sure if
enabled by default...

>

**Comment by AleksanderPopov** [comment]
Just tried to use Jest with selenidejs, and seems like there is only `Wait` selenidejs class in the stacktrace, not sure do we actually need that, will close for now, if anyone will need that in future, please feel free to request for reopen
