### ISSUE TITLE
Version 1.3.2 broke my xpath selector

### ISSUE THREAD

**Issue by ErmolaevNV** [KnowledgeExpert/selenidejs#131]
I am using the given selector for searching. However, when I updated to a new version, everything stopped working.

```
browser.element(`
    //pre[contains(.,'{"get":{"order_id":"${tOrderId}","sessid":"${tSessionId}","status":"${tStatus}"},"post":[]}')]
    `).getWebElement().then(() => {
            status = true;
        }).catch(() => {
            status = false;
        });
```

**Comment by alex-popov-tech** [comment]
@ErmolaevNV hello, can you provide more details?
What exactly not working, html chunk on which it is not working, etc.

**Comment by ErmolaevNV** [comment]
@alex-popov-tech 

<div class="card card-body">
    <code>
        <pre>{"get":{"order_id":"31483412","sessid":"E7E3E14C415672D0D18547066F367090","status":"CANCELED"},"post":[]}</pre>
    </code>
</div>

**Comment by alex-popov-tech** [comment]
@ErmolaevNV let me check, will get back to you

**Comment by alex-popov-tech** [comment]
@ErmolaevNV the problem possibly in your xpath, its contains spaces/linebreaks...
not sure if that will work for selenium, but i will push fix for that which will trim selector string just in case

**Comment by alex-popov-tech** [comment]
```
    await GIVEN.openedEmptyPageWithBody(` <div class="card card-body">
    <code>
        <pre>{"get":{"order_id":"31483412","sessid":"E7E3E14C415672D0D18547066F367090","status":"CANCELED"},"post":[]}</pre>
    </code>
</div>`);
    const tOrderId = '31483412';
    const tSessionId = 'E7E3E14C415672D0D18547066F367090';
    const tStatus = 'CANCELED';
    await browser
      .element(`
 //pre[contains(.,'{"get":{"order_id":"${tOrderId}","sessid":"${tSessionId}","status":"${tStatus}"},"post":[]}')]
`)
      .should(be.visible);
```
that code works for me now

**Comment by ErmolaevNV** [comment]
> ```
>     await GIVEN.openedEmptyPageWithBody(` <div class="card card-body">
>     <code>
>         <pre>{"get":{"order_id":"31483412","sessid":"E7E3E14C415672D0D18547066F367090","status":"CANCELED"},"post":[]}</pre>
>     </code>
> </div>`);
>     const tOrderId = '31483412';
>     const tSessionId = 'E7E3E14C415672D0D18547066F367090';
>     const tStatus = 'CANCELED';
>     await browser
>       .element(`
>  //pre[contains(.,'{"get":{"order_id":"${tOrderId}","sessid":"${tSessionId}","status":"${tStatus}"},"post":[]}')]
> `)
>       .should(be.visible);
> ```
> 
> that code works for me now

well, I'll try to find out what exactly breaks my xpath. The problem was solved by switching to version 1.3.1

**Comment by alex-popov-tech** [comment]
@ErmolaevNV you're using backticks with linebreaks, which means that string starts with a linebreak, and we were not expecting that :)

**Comment by ErmolaevNV** [comment]
@alex-popov-tech it really works, thanks!!! Now I can upgrade to 1.3.2 =)

**Comment by alex-popov-tech** [comment]
@ErmolaevNV should work with linebreaks in 1.3.3
