### ISSUE TITLE
How to select an option in select element?

### ISSUE THREAD

**Issue by ErmolaevNV** [KnowledgeExpert/selenidejs#132]
I have some html code:

```
<select required="" id="animals" name="animal" class="form-control">
  <option value="1">Dog</option>
  <option value="2">Cat</option>
  <option value="3">Gouse</option>
</select>
```
How to select an option with value = 3 (Gouse)?

```
await browser.element(`//select[@id='animals']`).????;
```

**Comment by alex-popov-tech** [comment]
did you try two clicks? on select and then on option

**Comment by ErmolaevNV** [comment]
> did you try two clicks? on select and then on option

This approach will work if Bootstrap DropDown is used https://getbootstrap.com/docs/4.6/components/dropdowns/
but the standard html selector is used here (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)

**Comment by alex-popov-tech** [comment]
you always can take raw element like `element.getWebElement()` and use element methods directly, there is something for selection...

**Comment by ErmolaevNV** [comment]
> you always can take raw element like `element.getWebElement()` and use element methods directly, there is something for selection...

Like what? I can't find anything better than:
```
    await browser.executeScript(`
        let id = $('option:contains("${text}")')[0].value;
        document.getElementById('animals').value = 3;
    `);
```
But it's terrible! =))

**Comment by alex-popov-tech** [comment]
hmmmm, true true...
well, you can do better like `element.executeScript(it => it.value = 3)`

**Comment by ErmolaevNV** [comment]
> hmmmm, true true...
> well, you can do better like `element.executeScript(it => it.value = 3)`

It's working thx!
