### ISSUE TITLE
driver.config vs Browser.config in default hooks (configuration.ts)

### ISSUE THREAD

**Issue by yashaka** [KnowledgeExpert/selenidejs#14]
see also #10 ...

```
        onFailureHooks: [
            async <T extends Driver | Element | Collection>(lastError: Error, entity: T, condition?: Condition<T>) => {
                const driver = Utils.getDriver(entity);
                if (driver.config.screenshotPath) {
                    const screenshotPath = await Utils.saveScreenshot(driver, Browser.config.screenshotPath);
```

o_O

what the difference between driver.config and Browser.config? should not it be the same style?

**Comment by AleksanderPopov** [comment]
yes, `Browser.config` and `driver.config` is usually the same object, so there should be `driver.config` in both cases.

**Comment by yashaka** [comment]
@AleksanderPopov 
hm...
but it gets not like that simple... see #10 also...
question is - if it is the same, why do we need to convert entity to driver to get driver's config, if we could just use Browser.config instead...

**Comment by AleksanderPopov** [comment]
the difference - `Browser` is just a bunch of methods from `Driver`, and it can be omitted in favor of `Driver`...so in failure hooks, we do want to get driver\config from arguments list

**Comment by yashaka** [comment]
@AleksanderPopov 
driver is an object... Browser is a namespace... 
looks not like the same thing)

**Comment by AleksanderPopov** [comment]
not relevant
