### ISSUE TITLE
Configuration.timeout and .hardTimeout looks a bit not self-documented enough...

### ISSUE THREAD

**Issue by yashaka** [KnowledgeExpert/selenidejs#15]
I am a bit concerned regarding names of timeout options... It's not obvious what is the difference... Additional documentation is needed to explain... Can we find the way to make it more self-documented?

**Comment by AleksanderPopov** [comment]
that property is from previos and deprecated version of selenidejs, we dont use that anymore. can be safely deleted.

**Comment by yashaka** [comment]
@AleksanderPopov 

the hardTimeout one?

yeah, sure... let's delete it... 

but nevertheless... we should have some "timeout" options in configurationn, right?

the classic ones are: timeout and pollingInterval... 

right now we have only timeout, right? and seems like pollingInterval is hardcoded:) no?

**Comment by yashaka** [comment]
By the way... 
yet, sometimes it's useful to have "hard wait"... original Selenide has it... - `Selenide.sleep()` or something like that...

question is do we need to add it, where, and with what name...

**Comment by AleksanderPopov** [comment]
There is no polling interval in selenidejs... Only timeout for waiting for conditions.

We can add `Browser.sleep` as an util method, since it sometimes can be really usefull...

**Comment by yashaka** [comment]
probably it's good to have pollingInterval as a configurable thing too... no?
@AleksanderPopov

**Comment by AleksanderPopov** [comment]
@yashaka what pros in waiting between pollings?

**Comment by BorisOsipov** [comment]
@AleksanderPopov cuz without waiting it easy to DDOS selenium server.

See https://github.com/webdriverio/webdriverio/issues/2406

**Comment by AleksanderPopov** [comment]
@BorisOsipov is following code

```
while(true) await driver.findElement(...)
```

will ddos selenium server?

As far as i know `await` should make js wait until promise resolved, to perform next line...so it should not send more requests than selenium can handle...or no?

**Comment by BorisOsipov** [comment]
Nope, but 

Promise.all[await driver.findElement(...),...... n] will.

**Comment by AleksanderPopov** [comment]
@BorisOsipov sure, we will try to avoid such constructions :)

**Comment by AleksanderPopov** [comment]
@BorisOsipov actually this is good point, there are several situations in project when we use `Promise.all`

**Comment by AleksanderPopov** [comment]
not relevant
