### ISSUE TITLE
'is' and 'isNot' don`t work properly

### ISSUE THREAD

**Issue by OlenaOKushnir** [KnowledgeExpert/selenidejs#21]
Both methods always return 'true'

**Comment by AleksanderPopov** [comment]
@OlenaOKushnir added new pr for that issue https://github.com/KnowledgeExpert/selenidejs/pull/22

**Comment by AleksanderPopov** [comment]
@OlenaOKushnir published in selenide:0.2.1, please confirm that problem do not reproduce

**Comment by AleksanderPopov** [comment]
both these methods covered by autotests now, closing this issue...
