### ISSUE TITLE
support for webdriver io

### ISSUE THREAD

**Issue by AleksanderPopov** [KnowledgeExpert/selenidejs#3]

**Comment by BorisOsipov** [comment]
How are you going to do it?

As I see there is hard dependencies to WebdriverJs...

I can't see how I can use this with wdio

**Comment by AleksanderPopov** [comment]
for now - yes, selenidejs is for official selenium webdriver, but since both webdriverio and webdriverjs implement WebDriver protocol, it should be possible to wrap selenidejs around any of them...

**Comment by BorisOsipov** [comment]
ok, let's rename this to support wdio as selenium webdriver binding library?
because now it sounds like selenidejs already supports wdio....

**Comment by AleksanderPopov** [comment]
sure, good point.

**Comment by AleksanderPopov** [comment]
probably its better to move that task in side of 'create webdriverio -> webdriver adapter', which is sounds like separate lib
