### ISSUE TITLE
do we need element.visibleElement(cssXpathOrBy) ?

### ISSUE THREAD

**Issue by yashaka** [KnowledgeExpert/selenidejs#85]
```
class Element { 
...
    visibleElement(cssOrXpathOrBy: string | By): Element {
        return this.all(cssOrXpathOrBy).elementBy(be.visible);
    }
```

So do we need element.visibleElement? why then not have browser.visibleElement?
won't it confuse? and hide some "smelly" parts for locators...
all.findBy(be.visible) is nevertheless not a standard/normal way to locate... it's kind of a workaround that happens from time to time... 
won't it be better to leave workarounds less shiny and so kind of highlighted in a code?
or should the name be more precise and verbose, like `firstVisibleElement`? (this probably is too much though...)

**Comment by AleksanderPopov** [comment]
maybe we can start from question - `why do we need that functionality?`

Is it so common case to have pages where we want to search for elements, and then take first visible?

@yashaka

**Comment by AleksanderPopov** [comment]
also, maybe `element.elementBy(be.visible)` the thing you need? @yashaka

**Comment by yashaka** [comment]
nooooooo:))))))

Hehe)

Actually I put this issue here, where I saw something like this in your original implementation:)

Probably let's follow the rule "if something looks like workaround - let's not create a special method/alias for it" :)
