### ISSUE TITLE
conditions implementation 2.0: move from lambdas to classes for cond1.or(cond2) add have.no.* & be.not.*

### ISSUE THREAD

**Issue by yashaka** [KnowledgeExpert/selenidejs#92]
currently we implement condition as common functions.
This allowed pretty simple impl in some context, in the beginning...
But implementinng them as objects of classes, may give the following benefits:
1. 
```
elements.filteredBy(have.cssClass('green').or(have.cssClass('red')))
```
over:
```
elements.filteredBy(or(have.cssClass('green'), have.cssClass('red')))
```

2. 
more robust implementation for have.no.*, be.not.*
without classes, the implementation will be of "hardcoded" style... (later will show an example if needed)

this have.no.* and be.not.* should also simplify implementation of condition-like methods.
We are going to remove shouldNot, waitUntilNot, and matchingNot. And there will be no need to add additional elementByNot and filteredByNot

**Comment by AleksanderPopov** [comment]
fixed in 1.2.0
